{-# OPTIONS_GHC -cpp #-}
{-# LANGUAGE CPP #-}

module Main where

import Data.List
import Data.Maybe
import System
import System.Console.GetOpt
import System.IO

import Types
import Log
import Stats
import Misc
import Formatter

version = "0.1.0"

showVersion = do putStrLn $ "hessu v" ++ version
exactVersion = do putStrLn $ "compiled on " ++ __DATE__ ++ " at " ++ __TIME__

header = "Usage: hessu INPUT OUTPUT"

buildOutput input output = do
    showVersion
    putStr $ "Opening file " ++ input ++ "... "
    inp <- readFile input
    putStrLn "success."
    putStr "Building stats... "
    let decoded = map (fromMaybe (Simple "") . (decode . (++ "\n"))) (lines inp)
    putStrLn "done."
    putStr "Writing file... "
    out <- openFile output WriteMode
    writeHeaders out input "style.css" decoded
    writeUsersTable out (take 25 ((reverse . qsort $ getUserStats decoded)))
    writeMiscStats out decoded
    hPutStrLn out (footer version)
    putStrLn " complete."
    hClose out

main = do
    argv <- getArgs
    case argv of
        []              -> buildOutput "sekopaat.log" "seko.html" --showVersion >> putStrLn header
        ["-v"]          -> showVersion >> exactVersion
        ["--version"]   -> showVersion >> exactVersion
        _               -> buildOutput (head argv) (last argv)

    --file <- readFile "suomipelit.log"
    --let decoded = map (fromMaybe (Simple "") . (decode . (++ "\n"))) (lines file)
    --putStrLn (intercalate "\n" (map (show) (reverse $ qsort (getUserStats decoded))))
    --headers "suomipelit.com"
    --    --putStrLn $ "Generated by " ++ version
    --footer
