-- hisg - IRC stats generator.
--
-- Copyright (c) 2009, 2010 Antoine Kalmbach <antoine dot kalmbach at jyu dot fi>
-- All rights reserved.
--
-- Redistribution and use in source and binary forms, with or without
-- modification, are permitted provided that the following conditions are met:
--     * Redistributions of source code must retain the above copyright
--       notice, this list of conditions and the following disclaimer.
--     * Redistributions in binary form must reproduce the above copyright
--       notice, this list of conditions and the following disclaimer in the
--       documentation and/or other materials provided with the distribution.
--     * Neither the name of the author nor the
--       names of its contributors may be used to endorse or promote products
--       derived from this software without specific prior written permission.
--
-- For further details, see LICENSE.

{-# OPTIONS_GHC -cpp -fglasgow-exts #-}
{-# LANGUAGE CPP #-}

module Main where

import Data.Maybe
import System.Console.GetOpt
import System.IO

import Control.Monad
import Control.Monad.Trans
import Control.Monad.State.Lazy

import Hisg.Core
import Hisg.IRCLog

version = "0.1.0"

showVersion = do putStrLn $ "hisg v" ++ version
exactVersion = do putStrLn $ "compiled on " ++ __DATE__ ++ " at " ++ __TIME__

header = "Usage: hisg INPUT OUTPUT"

runHisg :: HisgM ()
runHisg = do
    loadFile "sekopaat.log"
    processFiles

main = do
    showVersion
    runStateT runHisg (Hisg [])

--    argv <- getArgs
--    case argv of
--        []              -> buildOutput "sekopaat.log" "seko.html" --showVersion >> putStrLn header
--        ["-v"]          -> showVersion >> exactVersion
--        ["--version"]   -> showVersion >> exactVersion
--        _               -> buildOutput (head argv) (last argv)
--
    --file <- readFile "suomipelit.log"
    --let decoded = map (fromMaybe (Simple "") . (decode . (++ "\n"))) (lines file)
    --putStrLn (intercalate "\n" (map (show) (reverse $ qsort (getUserStats decoded))))
    --headers "suomipelit.com"
    --    --putStrLn $ "Generated by " ++ version
    --footer
    --
